import base64
import json
from io import BytesIO

import anthropic
import requests
from PIL import Image

DEFAULT_MODEL = "claude-opus-5-5"
MAX_IMAGE_SIDE = 512

_SCHEMA = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "description": {"type": "string"},
    },
    "required": ["title", "description"],
    "additionalProperties": False,
}

_client = None


def _get_client() -> anthropic.Anthropic:
    # Credentials resolve from the environment (ANTHROPIC_API_KEY or an `ant auth login` profile).
    global _client
    if _client is None:
        _client = anthropic.Anthropic(max_retries=5)
    return _client


def _fetch_image_b64(url: str) -> str:
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    img = Image.open(BytesIO(resp.content)).convert("RGB")
    img.thumbnail((MAX_IMAGE_SIDE, MAX_IMAGE_SIDE))
    buf = BytesIO()
    img.save(buf, format="JPEG", quality=90)
    return base64.standard_b64encode(buf.getvalue()).decode("utf-8")


def describe_product(image_url: str, product_type: str, tags: dict, model: str = DEFAULT_MODEL) -> dict:
    """Returns {"title": ..., "description": ...} generated by Claude from the product image."""
    tags_text = ", ".join(f"{k}: {v}" for k, v in tags.items() if v)
    prompt = (
        "You are writing an e-commerce listing for the fashion product in this image.\n"
        f"Product type: {product_type}\n"
        f"Known tags: {tags_text}\n\n"
        "Write a concise product title (max 12 words, no brand names unless clearly visible) "
        "and a 2-3 sentence description covering what is visible: color, material, cut and details. "
        "Do not invent sizes, prices or brands."
    )

    response = _get_client().beta.messages.create(
        model=model,
        max_tokens=2048,
        betas=["server-side-fallback-2026-07-01"],
        fallbacks="default",
        output_config={"effort": "low", "format": {"type": "json_schema", "schema": _SCHEMA}},
        messages=[{
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "source": {"type": "base64", "media_type": "image/jpeg", "data": _fetch_image_b64(image_url)},
                },
                {"type": "text", "text": prompt},
            ],
        }],
    )

    if response.stop_reason == "refusal":
        raise RuntimeError("request was declined")
    if response.stop_reason == "max_tokens":
        raise RuntimeError("response was truncated")
    text = next(b.text for b in response.content if b.type == "text")
    return json.loads(text)
